[project]
name = "ly-nvim"
version = "2.5.0"
edition = "0.4.1"

[[todo]]
name = "add vim-visual-mutli"
status = ""
description = ""
priority = 1
difficulty = 4

[[todo]]
name = "basic math config"
status = ""
description = ""
priority = 1
difficulty = 8

[[todo]]
name = "upgrade lsp config"
status = ""
description = ""
priority = 8
difficulty = 8

[[todo]]
name = "setup symbol renaming"
status = ""
description = ""
priority = 8
difficulty = 8

[[done]]
name = "notify"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "project handler"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "add shade"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "add twilight"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "upgrade keymap and which-key"
status = ""
description = ""
priority = 2
difficulty = 8

[[done]]
name = "upgrade harpoon config"
status = ""
description = ""
priority = 1
difficulty = 3

[[done]]
name = "basic lsp config"
status = ""
description = ""
priority = 8
difficulty = 8

[[done]]
name = "basic nvim-tree config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic telescope config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic treesitter config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic undotree config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic which-key config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic colorscheme config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic harpoon config"
status = ""
description = ""
priority = 1
difficulty = 1

[[done]]
name = "basic keybind config"
status = ""
description = ""
priority = 1
difficulty = 1
